var g="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};function k(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");}var l=k(this);
function n(a,c){if(c)a:{var b=l;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in b))break a;b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&g(b,a,{configurable:!0,writable:!0,value:c})}}n("Array.prototype.fill",function(a){return a?a:function(c,b,d){var e=this.length||0;0>b&&(b=Math.max(0,e+b));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(b=Number(b||0);b<d;b++)this[b]=c;return this}});function p(a){return a?a:Array.prototype.fill}
n("Int8Array.prototype.fill",p);n("Uint8Array.prototype.fill",p);n("Uint8ClampedArray.prototype.fill",p);n("Int16Array.prototype.fill",p);n("Uint16Array.prototype.fill",p);n("Int32Array.prototype.fill",p);n("Uint32Array.prototype.fill",p);n("Float32Array.prototype.fill",p);n("Float64Array.prototype.fill",p);
n("Math.hypot",function(a){return a?a:function(c){if(2>arguments.length)return arguments.length?Math.abs(arguments[0]):0;var b,d,e;for(b=e=0;b<arguments.length;b++)e=Math.max(e,Math.abs(arguments[b]));if(1E100<e||1E-100>e){if(!e)return e;for(b=d=0;b<arguments.length;b++){var h=Number(arguments[b])/e;d+=h*h}return Math.sqrt(d)*e}for(b=d=0;b<arguments.length;b++)h=Number(arguments[b]),d+=h*h;return Math.sqrt(d)}});
var q=document.getElementById("gamecanvas"),r=q.getContext("2d"),t=Array(40).fill(0),u=!1,v=!1;q.onmousedown=function(){v=!0};q.onmouseup=function(){v&&(u=!0);v=!1};var w=0,z=0;q.addEventListener("mousemove",function(a){var c=q.getBoundingClientRect();w=Math.round(a.clientX-c.left);z=Math.round(a.clientY-c.top)});
var A=[],B=!1,D=-10,E=!1,F=!1,I=10,J=[],P={a:K,as:L,z:function(){return B=!1},zs:function(){return B=!1},c:function(){return E=!1},v:function(){return F=!1},vs:function(){return F=!1},x:O},Q={z:function(){B=!0;D=-Math.abs(D)},zs:function(){B=!0;D=Math.abs(D)},c:function(){return E=!0},v:function(){F=!0;I=-Math.abs(D)},vs:function(){F=!0;I=Math.abs(D)}};document.onkeyup=function(a){a=a||window.event;a=(a.shiftKey?a.key+"s":a.key).toLowerCase();if(P[a])P[a]()};
document.onkeypress=function(a){a=a||window.event;a=(a.shiftKey?a.key+"s":a.key).toLowerCase();if(Q[a])Q[a]()};var R;
function S(a){R||(R=a);var c=a-R,b=.01*c;R=a;a=q.width=window.innerWidth;var d=q.height=window.innerHeight;r.fillStyle="black";r.fillRect(0,0,a,d);t.push(1E3/c);t.shift();c=t.reduce(function(e,h){return e+h})/t.length;r.fillStyle="white";r.font="30px Arial";r.fillText("FPS: "+Math.floor(c),20,40);r.fillText(""+A.length,20,80);J.forEach(function(e){r.fillStyle="green";r.fillRect(e.x,e.y,4,4)});T();u=!1;U(b);window.requestAnimationFrame(S)}window.requestAnimationFrame(S);
function U(a){var c=Math.random();A.forEach(function(b){if(.5<=c){var d=0,e=0,h=function(m,x,G,M){var N=Math.atan2(b.y-x,b.x-m);m=Math.hypot(b.y-x,b.x-m);x=1;(void 0===M||M)&&(x=1-m/800*.7);G*=x;d+=G*Math.cos(N);e+=G*Math.sin(N)};J.forEach(function(m){h(m.x,m.y,m.f)});B&&h(w,z,D);if(F){var y=-Math.abs(I),f=I,C=1-Math.hypot(b.y-z,b.x-w)/800*.8,H=Math.atan2(b.y-z,b.x-w);d+=y*Math.cos(H)*C;e+=y*Math.sin(H)*C;y=H-Math.PI/2;d+=f*Math.cos(y)*C;e+=f*Math.sin(y)*C}E&&(f=V(-25,Math.atan2(b.y-z,b.x-w)),b.i=
0,b.j=0,b.g=f.x,b.h=f.y);b.i=d;b.j=e;f=W(b.i,b.j,20);b.i=f.x;b.j=f.y}b.g+=a*b.i;b.h+=a*b.j;f=W(b.g,b.h,35);b.g=f.x;b.h=f.y;b.x+=a*b.g;b.y+=a*b.h;f=f.l;r.fillStyle="rgb("+Math.max(0,Math.min(255,26+f/35*229))+","+Math.max(0,Math.min(255,140+f/35*84))+","+Math.max(0,Math.min(255,255-f/35*153))+")";r.fillRect(b.x,b.y,1,1)})}function T(){if(u){A=[];for(var a=0;3E3>a;a++)A.push({x:Math.random()*window.innerWidth,y:Math.random()*window.innerHeight,g:0,h:0,i:0,j:0})}}
function O(){A.forEach(function(a){var c=V(35,360*Math.random());a.g=c.x;a.h=c.y})}function K(){J.push({x:w,y:z,f:-4})}function L(){for(var a=0;a<J.length;a++)if(50>=Math.hypot(w-J[a].x,z-J[a].y)){J.splice(a,1);break}};function V(a,c){return{x:a*Math.cos(c),y:a*Math.sin(c)}}function W(a,c,b){var d=Math.hypot(a,c),e=Math.atan2(c,a);return d>b?(a=V(b,e),{x:a.x,y:a.y,l:b}):{x:a,y:c,l:d}};
